%YAML:1.0
---
blade_model_path : "/home/ps/workspace/stitcher/blade_model/3505_ply"      # 铲刀模型保存路径
model_type : ".ply"                                   # 铲刀模型文件类型, .obj or .ply

front_wheel_center : !!opencv-matrix                  # 前轮相对于相机安装位置投影的坐标(即不考虑高度)，模型测量得到
  rows: 3                                             # x正为左，y正为前
  cols: 1                                             # 记为1号坐标系
  dt: f
  data: [ -0.062, -1.0, 0]

track_min_show_v: 1                                   # 车轮轨迹线开始绘制的位置

blade_color_0 : !!opencv-matrix                       # 铲刀大部分区域的颜色，黄色
  rows: 3
  cols: 1
  dt: f
  data: [ 0.714, 0.612, 0.325]

blade_color_1 : !!opencv-matrix                       # 铲刀油缸伸缩部分颜色，银色
  rows: 3
  cols: 1
  dt: f
  data: [ 0.8, 0.8, 0.8]

font_pixel_height: 50

need_update: 0    # 为1时可以调整后视车道线的参数，
                  # front_wheel_center 控制后视车道线起点的位置
                  # 地面方程由./parameters/yamls/ground.yaml 中的ground_matrix确定，也可以修改
                  # 影响效率，实际运行时需要设置为0


back_track_wait_time: 100           # ms，降低后视车道线刷新率